version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: promo-site-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/promo_site

  db:
    image: postgres:15.4
    container_name: promo-site-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - promo-site-db-data:/var/lib/postgresql/data

volumes:
  promo-site-db-data:
